#ifndef WORLD_CONFIG_H
#define WORLD_CONFIG_H

#define MAX_BOIDS 1800
#define BOID_SPEED 12
#define BOID_BASE_SIZE 20
#define BOID_SEPARATION_RADIUS 50
#define BOID_PERCEPTION_RADIUS 320
#define BOID_SEPARATION_STRENGTH 18.6f
#define BOID_ALIGNMENT_STRENGTH 14.f
#define BOID_COHESION_STRENGTH 9.75f

#define SCREEN_WIDTH 1366
#define SCREEN_HEIGHT 768
#define WORLD_WIDTH 12800.0
#define WORLD_HEIGHT 6400.0

#endif
