#ifndef WORLD_CONFIG_H
#define WORLD_CONFIG_H

#include <array>
#include <vector>

#define MAX_BOIDS 6000
#define BOID_SPEED 18
#define BOID_BASE_SIZE 20
#define BOID_SEPARATION_RADIUS 75
#define BOID_PERCEPTION_RADIUS 200
#define BOID_TO_WHOID_PERCEPTION_RADIUS 400
#define BOID_TO_WHOID_SEPARATION_STRENGTH 5.7f
#define BOID_SEPARATION_STRENGTH 5.8f
#define BOID_ALIGNMENT_STRENGTH 1.f
#define BOID_COHESION_STRENGTH .3f

#define MAX_WHOIDS 6
#define WHOID_SPEED 5
#define WHOID_SIZE 200
#define WHOID_PERCEPTION_RADIUS 800
#define WHOID_SEPARATION_STRENGTH 2.0f
#define EDGE_AVOIDANCE_STRENGTH 0.3f

#define SCREEN_WIDTH 1366
#define SCREEN_HEIGHT 768
#define WORLD_WIDTH 12800.0
#define WORLD_HEIGHT 6400.0

constexpr int CELL_SIZE = BOID_PERCEPTION_RADIUS;
constexpr int ROWS = (WORLD_HEIGHT + CELL_SIZE - 1) / CELL_SIZE;
constexpr int COLUMNS = (WORLD_WIDTH + CELL_SIZE - 1) / CELL_SIZE;
constexpr int ESTIMATE_BOID_DISTRIBUTION = (MAX_BOIDS / (ROWS * COLUMNS)) * 4;

using SpatialGrid = std::array<std::array<std::vector<int>, COLUMNS>, ROWS>;

#endif
