#ifndef WORLD_CONFIG_H
#define WORLD_CONFIG_H

#define MAX_BOIDS 1100
#define BOID_SPEED 12.0f
#define BOID_BASE_SIZE 20.0f
#define BOID_SEPARATION_RADIUS 50.0f
#define BOID_PERCEPTION_RADIUS 480.0f
#define BOID_TO_SQUOID_SEPARATION_STRENGTH 120.0f
#define BOID_SEPARATION_STRENGTH 35.0f
#define BOID_ALIGNMENT_STRENGTH 15.5f
#define BOID_COHESION_STRENGTH 7.5f

#define SCREEN_WIDTH 1366
#define SCREEN_HEIGHT 768
#define WORLD_WIDTH 6000
#define WORLD_HEIGHT 3000

#endif
