#version 430

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(std430, binding = 0) readonly buffer inputPosition {
  vec2 inPositionBuffer[];
};
layout(std430, binding = 1) readonly buffer inputVelocity {
  vec2 inVelocityBuffer[];
};

layout(std430, binding = 2) writeonly buffer outputPosition {
  vec2 outPositionBuffer[];
};
layout(std430, binding = 3) writeonly buffer outputVelocity {
  vec2 outVelocityBuffer[];
};

layout(location = 0) uniform int u_maxBoids;
layout(location = 1) uniform float u_alignmentStrength;
layout(location = 2) uniform float u_cohesionStrength;
layout(location = 3) uniform float u_separationStrength;
layout(location = 4) uniform float u_perceptionRadius;
layout(location = 5) uniform float u_separationRadius;
layout(location = 6) uniform float u_maxSpeed;
layout(location = 7) uniform float u_minSpeed;
layout(location = 8) uniform float u_frameTime;
layout(location = 9) uniform vec2 u_worldSpace;

vec2 normalizeVector(vec2 v) {
  float magnitude = sqrt((v.x * v.x) + (v.y * v.y));
  vec2 normalizedVec = (magnitude > 0.0) ? v / magnitude : v;

  return normalizedVec;
}

vec2 computeForce(vec2 sumDirection, float iBoidsInRange, vec2 currentVelocity,
                  float scaleStrength) {
  vec2 acceleration = vec2(0.0);
  if (iBoidsInRange == 0.0)
    return acceleration;

  sumDirection *= iBoidsInRange;
  sumDirection = normalizeVector(sumDirection) * u_maxSpeed;
  acceleration = sumDirection - currentVelocity;
  acceleration *= scaleStrength;

  return acceleration;
}

void main() {
  uint myIndex = gl_GlobalInvocationID.x;

  if (myIndex >= u_maxBoids)
    return;

  float perceptionRadiusSqr = (u_perceptionRadius * u_perceptionRadius);
  float separationRadiusSqr = (u_separationRadius * u_separationRadius);

  vec2 positionVector = inPositionBuffer[myIndex];
  vec2 velocityVector = inVelocityBuffer[myIndex];

  vec2 totalAcceleration = vec2(0.0);
  vec2 sumAlignment = vec2(0.0);
  vec2 sumSeparation = vec2(0.0);
  vec2 sumCohesion = vec2(0.0);

  float boidsInRange = 0.0;
  float boidsInSeparationRange = 0.0;

  for (int i = 0; i < u_maxBoids; ++i) {
    if (i == myIndex) {
      continue;
    }

    vec2 positionDifference = positionVector - inPositionBuffer[i];
    float distanceToFlockSqr =
        max(dot(positionDifference, positionDifference), 1.0);

    float minDistanceCheck = step(1.0, distanceToFlockSqr);
    float perceptionDistCheck =
        step(distanceToFlockSqr, perceptionRadiusSqr) * minDistanceCheck;
    float separationDistCheck =
        step(distanceToFlockSqr, separationRadiusSqr) * minDistanceCheck;

    vec2 separationDirection = (positionDifference) / distanceToFlockSqr;
    vec2 cohesionDirection = -positionDifference;

    sumAlignment += inVelocityBuffer[i] * perceptionDistCheck;
    sumCohesion += cohesionDirection * perceptionDistCheck;
    sumSeparation += separationDirection * separationDistCheck;

    boidsInRange += perceptionDistCheck;
    boidsInSeparationRange += separationDistCheck;
  }

  float iBoidsInRange = (boidsInRange > 0.0) ? 1.0 / boidsInRange : 0;
  vec2 alignmentAcceleration = computeForce(
      sumAlignment, iBoidsInRange, velocityVector, u_alignmentStrength);

  vec2 cohesionAcceleration = computeForce(sumCohesion, iBoidsInRange,
                                           velocityVector, u_cohesionStrength);

  vec2 separationAcceleration =
      (boidsInSeparationRange > 0.0)
          ? computeForce(sumSeparation, (1.0 / boidsInSeparationRange),
                         velocityVector, u_separationStrength)
          : vec2(0.0);

  totalAcceleration +=
      cohesionAcceleration + separationAcceleration + alignmentAcceleration;

  velocityVector += (totalAcceleration * u_frameTime);

  float speed = length(velocityVector);
  
  if (speed > u_maxSpeed) {
    velocityVector = normalizeVector(velocityVector) * u_maxSpeed;
  } else if (speed < u_minSpeed) {
    velocityVector = normalizeVector(velocityVector) * u_minSpeed;
  }

  positionVector += velocityVector;
  positionVector = mod(positionVector, u_worldSpace);

  outVelocityBuffer[myIndex] = velocityVector;
  outPositionBuffer[myIndex] = positionVector;
}
