#version 430

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout (std430, binding = 0) readonly buffer inputPosition {
    vec4 inPositionBuffer[];
};
layout (std430, binding = 1) readonly buffer inputVelocity {
    vec4 inVelocityBuffer[];
};

layout (std430, binding = 2) writeonly buffer outputPosition {
    vec4 outPositionBuffer[];
};
layout (std430, binding = 3) writeonly buffer outputVelocity {
    vec4 outVelocityBuffer[];
};

layout (location = 0) uniform int u_maxBoids;
layout (location = 1) uniform float u_alignmentStrength;
layout (location = 2) uniform float u_cohesionStrength;
layout (location = 3) uniform float u_separationStrength;
layout (location = 4) uniform float u_perceptionRadius;
layout (location = 5) uniform float u_separationRadius;
layout (location = 6) uniform float u_maxSpeed;
layout (location = 7) uniform float u_minSpeed;
layout (location = 8) uniform float u_frameTime;
layout (location = 9) uniform vec4 u_worldSpace;
layout (location = 10) uniform float u_scale;


vec3 safeNormalizeVector(vec3 v) {
    return v / (length(v) + 0.0001);
}

vec3 computeForce(vec3 sumDirection, float iBoidsInRange, vec3 currentVelocity,
                  float scaleStrength) {
    vec3 acceleration = vec3(0.0);
    float boidCheck = float(iBoidsInRange != 0);

    sumDirection *= iBoidsInRange;
    sumDirection = safeNormalizeVector(sumDirection) * u_maxSpeed;
    acceleration = (sumDirection - currentVelocity) * boidCheck;
    acceleration *= scaleStrength;

    return acceleration;
}

void main() {
    uint myIndex = gl_GlobalInvocationID.x;

    if (myIndex >= u_maxBoids) {
        return;
    }
    float perceptionRadiusSqr = (u_perceptionRadius * u_perceptionRadius) * u_scale;
    float separationRadiusSqr = (u_separationRadius * u_separationRadius) * u_scale;

    vec3 positionVector = inPositionBuffer[myIndex].xyz;
    vec3 velocityVector = inVelocityBuffer[myIndex].xyz;

    vec3 targetDirection = vec3(0.0);
    vec3 sumAlignment = vec3(0.0);
    vec3 sumSeparation = vec3(0.0);
    vec3 sumCohesion = vec3(0.0);

    float boidsInRange = 0.0;
    float boidsInSeparationRange = 0.0;

    for (int i = 0; i < u_maxBoids; ++i) {
        if (i == myIndex) {
            continue;
        }

        vec3 positionDifference = positionVector - inPositionBuffer[i].xyz;
        float distanceToFlockSqr = max(dot(positionDifference, positionDifference), 0.1);

        float minDistanceCheck = step(0.1, distanceToFlockSqr);
        float perceptionDistCheck = step(distanceToFlockSqr, perceptionRadiusSqr) * minDistanceCheck;
        float separationDistCheck = step(distanceToFlockSqr, separationRadiusSqr) * minDistanceCheck;

        vec3 separationDirection = (positionDifference) / distanceToFlockSqr;
        vec3 cohesionDirection = -positionDifference;

        sumAlignment += inVelocityBuffer[i].xyz * perceptionDistCheck;
        sumCohesion += cohesionDirection * perceptionDistCheck;
        sumSeparation += separationDirection * separationDistCheck;

        boidsInRange += perceptionDistCheck;
        boidsInSeparationRange += separationDistCheck;
    }

    float iBoidsInRange = 1 - float(boidsInRange == 0.0) / 0.00001 + boidsInRange; // evil math hack
    float iBoidsInSeparationRange = 1 - float(boidsInSeparationRange == 0.0) / 0.0001 + boidsInSeparationRange;

    vec3 alignmentAcceleration = computeForce(sumAlignment, iBoidsInRange, velocityVector, u_alignmentStrength);
    vec3 cohesionAcceleration = computeForce(sumCohesion, iBoidsInRange, velocityVector, u_cohesionStrength);
    vec3 separationAcceleration = computeForce(sumSeparation, iBoidsInSeparationRange, velocityVector, u_separationStrength);

    targetDirection += cohesionAcceleration + separationAcceleration + alignmentAcceleration;
    velocityVector += (targetDirection * u_frameTime);

    velocityVector = safeNormalizeVector(velocityVector) * u_maxSpeed;

    positionVector += velocityVector;
    positionVector = mod(positionVector, u_worldSpace.xyz);

    outVelocityBuffer[myIndex] = vec4(velocityVector, 0.0);
    outPositionBuffer[myIndex] = vec4(positionVector, 0.0);
}
